### ISSUE TITLE
MVP tracking issue

### ISSUE THREAD

**Issue by ehuss** [rust-lang/wg-cargo-std-aware#10]
This issue is for tracking the initial MVP implementation for std-aware Cargo.

Work should soon begin on enabling Cargo to build the standard library with a project. This is an experiment that is not intended to be useful, but is primarily intended to work through implementation issues. There will be no UI other than a nightly `-Z` flag to enable this behavior. This will likely only work on a small subset of supported platforms, perhaps just Linux or macOS.

Follow this issue for notifications on the status of this work.

**Comment by Ericson2314** [comment]
https://github.com/rust-lang/cargo/pull/2768 this was my old MVP implementation in case it is useful. See @Cardoe's rebase in ge last comment, which should be easier to rebase yet again.

**Comment by ehuss** [comment]
This is now on the latest nightly, with some basic documentation mentioned in the PR at https://github.com/rust-lang/cargo/pull/7216.
