### ISSUE TITLE
Support `cargo fetch`

### ISSUE THREAD

**Issue by ehuss** [rust-lang/wg-cargo-std-aware#22]
The `cargo fetch` command currently does not know about std dependencies.

**Comment by jyn514** [comment]
I'm willing to work on this, I have a half-functioning prototype locally.

**Comment by ehuss** [comment]
Nice! Let me know if you have any questions.

**Comment by ehuss** [comment]
This should be resolved by https://github.com/rust-lang/cargo/pull/10129.
