### ISSUE TITLE
Investigate custom libdir setting

### ISSUE THREAD

**Issue by ehuss** [rust-lang/wg-cargo-std-aware#48]
Cargo assumes a specific sysroot layout (primarily [here](https://github.com/rust-lang/cargo/blame/ab6fa8908c9b6c8f7e2249231c395eebfbc49891/src/cargo/core/compiler/layout.rs#L191)).  However, rustc may be built in such a way that the lib directory name is different from the default of "lib".  This is via `install.libdir` in `config.toml`.  See [`find_libdir`](https://github.com/rust-lang/rust/blob/37538aa1365d1f8a10770a7d15c95b3167c8db57/src/librustc/session/filesearch.rs#L144-L169).

I was unable to find any targets built by rust-lang that set this parameter.  Rumor is that some linux distributions may set it (to things like "lib32" or "lib64"), but I cannot find any active linux distribution that does that.

This needs investigation to understand the impact, and what needs to be done.  AFAIK, `rustc` cannot be queried for this path, so there is no way to discover how it is compiled.

**Comment by ehuss** [comment]
Note: Switch to `--print=target-libdir` once 1.43 is stable: https://github.com/rust-lang/rust/pull/69608

**Comment by Ericson2314** [comment]
Per https://github.com/rust-lang/wg-cargo-std-aware/issues/49#issuecomment-550431175 wasn't this stuff going away anyways?

**Comment by ehuss** [comment]
Oh, hmm.  Yea, it was removed in https://github.com/rust-lang/cargo/pull/7699.

Cargo still uses the libdir for some other dylib nonsense, but it is not related to build-std.  Closing since this seems resolved, thanks!
