### ISSUE TITLE
cannot produce proc-macro on musl host toolchain

### ISSUE THREAD

**Issue by 12101111** [rust-lang/wg-cargo-std-aware#52]
Programs on musl target normally statically link to musl libc, but can dynamically link using

```shell
RUSTFLAGS="-C target-feature=-crt-static" cargo build
```

see: https://github.com/rust-lang/rust/issues/59302

However, when building a uefi crate, the RUSTFLAGS don't work.

```shell
$ cargo build -Z build-std=core --target=x86_64-unknown-uefi
error: cannot produce proc-macro for `uefi-macros v0.2.1` as the target `x86_64-unknown-linux-musl` does not support these crate types
```

**Comment by alexcrichton** [comment]
Thanks for the report, but I don't think that this bug is related to `-Zbuild-std`. This is an issue with just using Cargo in general with `--target`.
