### ISSUE TITLE
Can we tailor the version of the compiler-builtins package that is compiled and linked together with the core crate?

### ISSUE THREAD

**Issue by parraman** [rust-lang/wg-cargo-std-aware#61]
We would like to know if it is currently possible to change the version of the compiler-builtins package that is compiled together with the core crate.

We are having [problems](https://github.com/rust-lang/compiler-builtins/issues/390) with the current version of `compiler-builtins` on the `sparc-unknown-linux-gnu` target. A new version has been produced to fix the issue. However, we are not able to test it because we cannot prevent the original one from being included. We would like to be able to link the new version, which is stored on a separate branch, instead of the current version.

We cannot add a dependency to the other version of the package into our `Cargo.toml` file because then cargo will include both versions and generate a linking error telling us that there are currently two versions of the same functions.

**Comment by SimonSapin** [comment]
Not knowing much about all this, it sounds like something that should be tested within the `rust-lang/rust` repository instead of using Cargo’s `build-std`.

**Comment by ehuss** [comment]
It is currently not possible to change the version with `build-std`.  As @SimonSapin mentioned, typically testing should be done by updating it in a clone of the `rust-lang/rust` repository and building `rustc` from there.  Assuming things work, anyone is welcome to post a PR to bump the version (see https://github.com/rust-lang/rust/pull/78209 for an example).

Supporting custom code with `build-std` is tracked in #7, though there isn't much of a plan or strategy on how that will work, yet.

**Comment by grbd** [comment]
I also ran into this exact same problem while trying to use a custom version of compiler_builtins on disk
while using xtensa-esp32-none-elf with build-std (uses a separate rustc llvm fork)

**Comment by ehuss** [comment]
Closing per the comment in https://github.com/rust-lang/wg-cargo-std-aware/issues/61#issuecomment-732307852.
